# Generated by Django 5.0.2 on 2026-05-26 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('reporting_currency', models.CharField(default='USD', max_length=3)),
                ('ghg_protocol_boundary', models.CharField(default='operational_control', help_text='GHG Protocol consolidation approach: operational_control | equity_share | financial_control', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('UTILITY', 'Utility Electricity (Green Button ESPI)'), ('SAP', 'SAP Procurement CSV'), ('TRAVEL', 'Corporate Travel (Concur/Navan)')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial — some rows failed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('validation_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='backend.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_werks_code', models.CharField(blank=True, db_index=True, help_text='SAP plant code (WERKS field). Used for procurement data joins.', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='backend.organization')),
            ],
            options={
                'ordering': ['country', 'name'],
                'unique_together': {('organization', 'sap_werks_code')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct Emissions (Fuel, Gas)'), (2, 'Scope 2 — Indirect Emissions (Purchased Electricity)'), (3, 'Scope 3 — Value Chain Emissions (Travel, Supply Chain)')])),
                ('source_type', models.CharField(choices=[('UTILITY', 'Utility Electricity (Green Button ESPI)'), ('SAP', 'SAP Procurement CSV'), ('TRAVEL', 'Corporate Travel (Concur/Navan)')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — Awaiting analyst review'), ('VALIDATED', 'Validated — Actual meter/source read'), ('ESTIMATED', 'Estimated — Meter read was estimated; needs reconciliation'), ('APPROVED', 'Approved — Sign-off complete, eligible for reporting'), ('REJECTED', 'Rejected — Record excluded from reporting'), ('SUPERSEDED', 'Superseded — Replaced by a corrected record')], db_index=True, default='PENDING', max_length=20)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('kg_co2e', models.DecimalField(decimal_places=4, help_text='CO2 equivalent in kilograms. Always stored in kg; convert to tonnes for reporting.', max_digits=14)),
                ('raw_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=20)),
                ('emission_factor_version', models.CharField(default='DEFRA 2023', help_text='The emission factor dataset version used for this calculation. Records must NOT be silently recalculated when factors update.', max_length=100)),
                ('emission_factor_value', models.DecimalField(blank=True, decimal_places=6, help_text='The exact factor applied (kg CO2e per unit) for auditability.', max_digits=10, null=True)),
                ('raw_payload', models.JSONField(help_text='Immutable original source data (CSV row, API response, etc.). Never modified after creation. Required for audit and dispute resolution.')),
                ('espi_quality_of_reading', models.CharField(blank=True, help_text="Green Button ESPI qualityOfReading code. '14'=Validated, '8'=Estimated.", max_length=5)),
                ('employee_id', models.CharField(blank=True, db_index=True, help_text='Employee identifier for Scope 3 travel records.', max_length=50)),
                ('travel_category', models.CharField(blank=True, help_text='FLIGHT | HOTEL | GROUND_TRANSPORT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_comment', models.TextField(blank=True, help_text='Free-text analyst note recorded at approval or rejection.')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_emission_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emission_records', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='backend.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='backend.organization')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='backend.emissionrecord')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'indexes': [
                    models.Index(fields=['organization', 'scope', 'period_start'], name='backend_emi_organiz_f876ef_idx'),
                    models.Index(fields=['organization', 'status'], name='backend_emi_organiz_d07a9b_idx'),
                    models.Index(fields=['organization', 'source_type', 'period_start'], name='backend_emi_organiz_28ad2a_idx'),
                    models.Index(fields=['employee_id', 'period_start'], name='backend_emi_employe_de413e_idx'),
                ],
            },
        ),
    ]
